apps/core/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home_view, name="home"),
    path("home/following/", views.following_view, name="following"),
    path("messages/", views.messages_view, name="messages"),
    path("bookmarks/", views.bookmarks_view, name="bookmarks"),
    path("@<str:username>/posts/", views.profile_view, name="profile"),
    path("@<str:username>/replies/", views.profile_replies_view, name="profile_replies"),
    path("@<str:username>/likes/", views.profile_likes_view, name="profile_likes"),
    path("@<str:username>/settings/", views.profile_settings_view, name="profile_settings"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("notifications/fetch", views.get_unread_notifications, name="fetch_notifications"),
    path("change-theme/", views.change_theme, name="change_theme"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("post/", include("apps.posts.urls")),
    path("", include("apps.core.urls")),
    path("", include("apps.chat.urls")),
    path("", include("apps.accounts.urls")),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/posts/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
import uuid

from django.urls import reverse

MAX_CONTENT_LENGTH = 350
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_posts")
    post_key = models.UUIDField(
        default=uuid.uuid4, max_length=40, unique=True, editable=False)
    parent_post = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE, related_name="replies")
    post_content = models.TextField(
        max_length=MAX_CONTENT_LENGTH, blank=False, null=False)
    datetime = models.DateTimeField(auto_now_add=True)
    media = models.FileField(upload_to='post-media', blank=True, null=True)
    views_count = models.IntegerField(default=0)
    reposted_by = models.ManyToManyField(User, blank=True, through="Repost", related_name="reposts")
    likes = models.ManyToManyField(User, blank=True, through="Like", related_name='post_likes')
    bookmarks = models.ManyToManyField(User, blank=True, through="Bookmark", related_name='post_bookmarks')
    modified = models.BooleanField(default=False)
    is_reply = models.BooleanField(default=False)
    is_video = models.BooleanField(default=False)

    def __str__(self):
        parent_post_info = f"{self.parent_post.user.username} on {self.parent_post.post_key}" if self.parent_post else self.post_key
        return f"{self.user.username}-{parent_post_info}"
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"username": self.user.username, "post_key": self.post_key})
    
    def clean(self):
        if len(self.post_content) > MAX_CONTENT_LENGTH:
            raise ValidationError(
                f"Post content cannot exceed {MAX_CONTENT_LENGTH} characters.")
        if self.is_video and not self.media:
            raise ValidationError(f"Video posts must have a media uploaded.")
        
    class Meta:
        ordering = ['-datetime']
        

class Repost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="u_reposts")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="p_reposts")
    datetime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Reposted: {self.post} by {self.user.username}"
    
    class Meta:
        ordering = ['-datetime']


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="u_likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="p_likes")
    datetime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Liked: {self.post} by {self.user.username}"
    
    class Meta:
        ordering = ['-datetime']


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="u_bookmarks")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="p_bookmarks")
    datetime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Bookmarked: {self.post} by {self.user.username}"
    
    class Meta:
        ordering = ['-datetime']


class Notification(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    post_creator = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)

apps/core/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from itertools import chain
from django.urls import reverse_lazy
from django.db.models import Count

from apps.accounts import forms
from apps.accounts.models import Profile
from apps.posts.models import Post, Repost, Notification
from utils.utils import get_posts_from_page


User = get_user_model()


def index(request):
    if request.user.is_authenticated:
        return redirect("home")
    return render(request, "_base.html", {"page_title": "join"})


@login_required
def home_view(request):
    post_list = Post.objects.filter(is_reply=False)
    posts = get_posts_from_page(post_list, request.GET.get('page', 1))

    context = {
        "page_title": "home",
        "first_page": request.GET.get('page', 1) == 1,
        "posts": posts,
    }

    return render(request, "core/home.html", context)


@login_required
def following_view(request):
    following_users = request.user.profile.following.select_related("profile")
    following_posts = Post.objects.filter(
        user__profile__in=following_users, is_reply=False).select_related('user__profile')
    following_reposts = Repost.objects.filter(
        user__profile__in=following_users).select_related('post', 'user__profile')

    combined_qs = sorted(
        chain(following_posts, following_reposts),
        key=lambda obj: obj.datetime,
        reverse=True
    )

    for index, post in enumerate(combined_qs):
        if isinstance(post, Repost):
            post.post.repost_user = post.user
            combined_qs[index] = post.post

    posts = get_posts_from_page(combined_qs, request.GET.get('page', 1))

    context = {
        "page_title": "home",
        "visible": True,
        "posts": posts,
        "first_page": request.GET.get('page', 1) == 1
    }
    return render(request, "core/following.html", context)


@login_required
def profile_view(request, username):
    user = User.objects.prefetch_related("user_posts").get(username=username)
    post_list = user.user_posts.filter(is_reply=False)
    reposts = Repost.objects.filter(user=user)

    combined_qs = sorted(
        chain(post_list, reposts),
        key=lambda obj: obj.datetime,
        reverse=True
    )

    for index, post in enumerate(combined_qs):
        if isinstance(post, Repost):
            post.post.repost_user = post.user
            combined_qs[index] = post.post

    posts = get_posts_from_page(combined_qs, request.GET.get('page', 1))

    context = {
        "page_title": username,
        "user": user,
        "posts": posts,
        "first_page": request.GET.get('page', 1) == 1
    }
    return render(request, "core/profile.html", context)


@login_required
def profile_replies_view(request, username):
    page = request.GET.get('page', 1)
    first_page = page == 1

    user = User.objects.prefetch_related("user_posts").get(username=username)
    post_list = user.user_posts.filter(is_reply=True)

    posts = get_posts_from_page(post_list, page)

    context = {
        "page_title": f"{username} Replies",
        "posts": posts,
        "user": user,
        "first_page": first_page
    }
    return render(request, "core/profile_replies.html", context)


@login_required
def profile_likes_view(request, username):
    page = request.GET.get('page', 1)
    first_page = page == 1

    user = User.objects.prefetch_related("u_likes").get(username=username)
    post_list = list(user.u_likes.all())

    for index, like_object in enumerate(post_list):
        post_list[index] = like_object.post

    posts = get_posts_from_page(post_list, page)

    context = {
        "page_title": f"{username} Likes",
        "posts": posts,
        "user": user,
        "first_page": first_page
    }
    return render(request, "core/profile_likes.html", context)


@login_required
def profile_settings_view(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile_settings', username=request.user.username)
    else:
        form = forms.ProfileForm(instance=profile)

    if request.user != user:
        return render(request, "core/error_page.html", {"message": "You don't have access to this page"})

    context = {
        "page_title": f"{username} Settings",
        "form": form,
        "first_page": True
    }

    return render(request, "core/profile_settings.html", context)


@login_required
def bookmarks_view(request):
    page = request.GET.get('page', 1)
    first_page = page == 1

    bookmarks = list(request.user.u_bookmarks.all())

    for index, bookmark_object in enumerate(bookmarks):
        bookmarks[index] = bookmark_object.post

    posts = get_posts_from_page(bookmarks, page)

    context = {
        "page_title": "bookmarks",
        "posts": posts,
        "first_page": first_page
    }
    return render(request, "core/bookmarks.html", context)


@login_required
def notifications_view(request):
    notifications = Notification.objects.filter(
        receiver=request.user).order_by("-timestamp")

    if request.method == "POST":
        Notification.objects.filter(id=request.POST["id"]).update(is_read=True)
        return HttpResponse("")

    if request.method == "DELETE":
        notifications.delete()

    context = {
        "page_title": "notifications",
        "notifications": notifications,
    }

    return render(request, "core/notifications.html", context)


@login_required
def get_unread_notifications(request):
    notifications = Notification.objects.filter(
        receiver=request.user, is_read=False).order_by("-timestamp")
    return render(request, 'core/includes/new_notification.html', {"notifications": notifications})


@login_required
def messages_view(request):
    chatrooms = request.user.chat_rooms.annotate(
        message_count=Count('chat_messages')
    ).filter(message_count__gte=1)

    chat_partners = User.objects.exclude(
        id=request.user.id).filter(chat_rooms__in=chatrooms)

    context = {
        "page_title": "messages",
        "chatrooms": chatrooms,
        "members": chat_partners,
    }
    return render(request, "core/messages.html", context)


@login_required
def change_theme(request):
    if request.method == 'POST':
        theme = request.POST["theme-dropdown"]
        request.session['theme'] = theme
        return HttpResponse(status=200)
    return HttpResponse(status=400)

templates/core/bookmarks.html
{% extends base_template %}

{% block title %}Bookmarks{% endblock title %}

{% block content %}
    {% if first_page %}
    <h2 class="text-xl px-4 py-2 border-slate-500 border-b-2 border-opacity-50">Bookmarks</h2>
    <script>
        window.scrollTo({ top: 0, behavior: "instant" });
    </script>
    {% endif %}

    {% include "core/includes/post_page.html" %}

{% endblock content %}

templates/core/error_page.html
{% extends base_template %}

{% block content %}
    <div class="w-full p-4 flex justify-center">
        <span class="text-2xl">{{ message }}</span>
    </div>
{% endblock content %}

templates/core/following.html
{% extends "core/home.html" %}

{% block home_content %}
    {% include "core/includes/post_page.html" %}
{% endblock home_content %}

templates/core/home.html
{% extends base_template %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Home{% endblock title %}

{% block content %}

    {% if first_page %}
    <div 
        role="tablist"
        class="tabs tabs-bordered pt-2 shrink" 
        hx-target="#content"
        hx-push-url="true"
        hx-swap="outerHTML">
        <a 
            role="tab" class="tab text-base {% if "following" not in request.path %}tab-active{% endif %}"
            hx-get="{% url "home" %}">
            For you
        </a>
        <a 
            role="tab" class="tab text-base {% if "following" in request.path %}tab-active{% endif %}" 
            hx-get="{% url "following" %}">
            Following
        </a>
    </div>

    <div class="home-section" id="home-page">
        <div class="post-form border-slate-500 border-b-2 border-opacity-50 max-sm:hidden">
            {% include "posts/post_form.html" with placeholder="What is happening?" %}
        </div>
    </div>
    <div id="feed-update"></div>   
    <script>
        if (document.getElementById("home-page")) {
            window.scrollTo({ top: 0, behavior: "instant" });
        }
    </script>
    {% endif %}

    {% block home_content %}
        {% include "core/includes/post_page.html" %}
    {% endblock home_content %}

{% endblock content %}

templates/core/messages.html
{% extends base_template %}

{% block title %}Messages{% endblock title %}

{% block content %}
    <div class="text-xl px-4 py-2 border-slate-500 border-b-2 border-opacity-50 flex items-center justify-between">
        <span>Messages</span>
    </div>
    <div class="flex">
        <dialog id="search_user" class="modal modal-bottom sm:modal-middle" _="init me.close()">
        <div class="modal-box flex justify-between items-start">
            <div class="flex flex-col">
                <input 
                type="search" 
                name="search" 
                hx-post="{% url "search" %}"
                hx-trigger="input changed delay:500ms, search"
                hx-target="#search-results"
                class="input input-bordered focus:outline-none rounded-full" 
                placeholder="Search a user..."
                _="init set my value to ''">
                <div 
                id="search-results" 
                class="flex flex-col" 
                _="init remove my children"
                ></div>
            </div>
            <div class="modal-action m-0">
                <form method="dialog">
                    <button class="btn btn-ghost btn-circle">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                        </svg>                              
                    </button>
                </form>
            </div>
        </div>
        </dialog>
    </div>

    <div class="flex border-b-2 border-slate-500 border-opacity-50">

        <div id="recents" class="h-[50vh] border-slate-500 border-r-2 border-opacity-50 w-[100px] overflow-y-auto">
            <button class="p-2 flex m-auto rounded-full hover:bg-base-300" onclick="search_user.showModal()" title="Add new user">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>                  
            </button>
            {% for member in members %}
                <div 
                class="cursor-pointer"
                hx-get="{% url "start_chat" username=member.username %}"
                hx-target="#content"
                hx-swap="outerHTML"
                hx-push-url="true"
                >
                    <div class="flex justify-center items-center m-auto mx-4 py-2" title="@{{ member.username }}">
                        <img src="{{ member.profile.profile_picture.url }}" alt="{{ member.username }}" class="w-10">
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="basis-full">
            {% block chat %}
            <div class="w-full h-full flex justify-center items-center">
                <span class="text-xl">Start a conversation</span>
            </div>
            {% endblock chat %}
        </div>

    </div>


{% endblock content %}

templates/core/notifications.html
{% extends base_template %}

{% block title %}Notifications{% endblock title %}

{% block content %}
    <div class="text-xl px-4 py-2 border-slate-500 border-b-2 border-opacity-50 flex justify-between items-center" _="init go to the top of the body">
        Notifications
        <button 
            class="btn btn-xs btn-outline btn-error"
            hx-delete="{% url "notifications" %}"
            hx-target="#content"
            hx-swap="outerHTML"
        >Clear</button>
    </div>

    <div id="alert-new"></div>

    <div 
    id="notifications"
    class="post-section"
    _="init add .hidden to .notification-indicator"
    >
        {% for notification in notifications %}
            {% if not notification.is_read %}
                <span 
                hx-post="{% url "notifications" %}" 
                hx-trigger="revealed" 
                hx-vals='{"id":"{{notification.id}}"}' 
                ></span>
            {% endif %}
            <article
            class="border-slate-500 border-b-2 border-opacity-50"
            hx-target="#content" 
            hx-swap="outerHTML" 
            hx-push-url="true"
            hx-get="{{ notification.post_creator.get_absolute_url }}"
            >
                {% include "posts/post.html" with post=notification.post_creator %}
            </article>
        {% endfor %}
    </div>
    
{% endblock content %}

templates/core/profile.html
{% extends base_template %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block content %}
    {% if first_page %}
    <div class="p-3 flex-fol">
        <div class="flex">

            <div class="min-w-16">
                <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.username }}" class="rounded-full w-16 h-16">
            </div>
            <div class="ps-4 flex flex-col w-full">
                <strong class="text-2xl">{{ user.profile.display_name }}</strong>
                {% if request.user != user %}
                    {% include "posts/partials/follow_section.html" with username=user.username profile=user.profile %}
                    <a 
                    class="btn btn-sm btn-outline btn-error w-fit ms-auto me-0 mt-2 no-animation"
                    hx-get="{% url "start_chat" username=user.username %}"
                    hx-target="#content"
                    hx-swap="outerHTML"
                    hx-push-url="true"
                    >Chat</a>
                {% else %}
                    <div>
                        <span class="pe-2"><strong>{{ user.profile.get_follower_count }}</strong> Followers</span>
                        <span class="pe-2"><strong>{{ user.profile.get_following_count }}</strong> Following</span>
                    </div>
                {% endif %}
            </div>
        </div>

        {% if user.profile.bio %}
        <blockquote>
            <p class="text-sm my-6 ms-2 me-8 border-t-2 border-slate-500 border-opacity-50 bio">{{ user.profile.bio }}</p>
        </blockquote>
        {% endif %}

    </div>

    <div 
        role="tablist"
        class="tabs tabs-bordered" 
        hx-target="#content"
        hx-push-url="true"
        hx-swap="outerHTML">
        <a 
            role="tab" class="tab text-base {% if "posts" in request.path %}tab-active font-bold{% endif %}" 
            hx-get="{% url "profile" username=user.username %}">
            Posts
        </a>
        <a 
            role="tab" class="tab text-base {% if "replies" in request.path %}tab-active font-bold{% endif %}" 
            hx-get="{% url "profile_replies" username=user.username %}">
            Replies
        </a>
        <a 
        role="tab" class="tab text-base {% if "likes" in request.path %}tab-active font-bold{% endif %}" 
        hx-get="{% url "profile_likes" username=user.username %}">
            Liked
        </a>
        {% if user == request.user %}
        <a 
        role="tab" class="tab text-base {% if "settings" in request.path %}tab-active font-bold{% endif %}" 
        hx-get="{% url "profile_settings" username=user.username %}">
            Settings
        </a>
        {% endif %}
    </div>
    <script>
        window.scrollTo({ top: 0, behavior: "instant" });
    </script>
    {% endif %}

    {% block profile_content %}
        {% include "core/includes/post_page.html" %}
    {% endblock profile_content %}
    
{% endblock content %}

templates/core/profile_likes.html
{% extends "core/profile.html" %}

{% block profile_content %}
    {% include "core/includes/post_page.html" %}
{% endblock profile_content %}

templates/core/profile_replies.html
{% extends "core/profile.html" %}

{% block profile_content %}
    {% include "core/includes/post_page.html" with reply="true" %}
{% endblock profile_content %}

templates/core/profile_settings.html
{% extends "core/profile.html" %}
{% load widget_tweaks %}

{% block profile_content %}
<div id="settings" class="">

    <div class="py-3 flex flex-col">
        <div class="flex flex-col items-center justify-center">
            <span class="text-xl">Background</span>
            
            <div class="join flex justify-center py-4" _="init call themeController()">
                <input type="radio" name="theme-dropdown" class="btn theme-controller join-item" aria-label="Dark" hx-post="{% url "change_theme" %}" value="dark"/>
                <input type="radio" name="theme-dropdown" class="btn theme-controller join-item" aria-label="Light" hx-post="{% url "change_theme" %}" value="light"/>
                <input type="radio" name="theme-dropdown" class="btn theme-controller join-item" aria-label="Nord" hx-post="{% url "change_theme" %}" value="nord"/>
                <input type="radio" name="theme-dropdown" class="btn theme-controller join-item" aria-label="Sunset" hx-post="{% url "change_theme" %}" value="sunset"/>
                <input type="radio" name="theme-dropdown" class="btn theme-controller join-item" aria-label="Retro" hx-post="{% url "change_theme" %}" value="retro"/>
            </div>
        </div>

        <div class="divider"></div>
        <div class="w-[75%] m-auto flex flex-col items-center">
            <span class="text-xl">Edit profile info</span>
            <form 
            enctype="multipart/form-data"
            method="POST"
            action="{% url "profile_settings" username=request.user.username %}"
            class="flex flex-col"
            id="edit-form"
            >
                {% csrf_token %}
                <div class="pt-3">
                    <label for="dn" class="label">Display name</label>
                    {% render_field form.display_name class="input input-bordered focus:outline-none w-full" id="dn" placeholder="Display name" %}
                </div>
                <div class="pt-3">
                    <label for="bio" class="label">Bio</label>
                    {% render_field form.bio class="textarea textarea-bordered focus:outline-none h-40 resize-none w-full" id="bio" placeholder="Bio" %}
                </div>
                <div class="hidden">
                    {% render_field form.profile_picture id="id_media" %}
                </div>
                <div class="pt-3">
                    <label 
                        for="id_media" 
                        id="setUpPreview" 
                        class="custom-file-upload bx-tool rounded-full p-1 flex"
                        _="on click call setUpImagePreview()"
                    >
                        <i class='bx bx-image-alt m-auto'></i>
                    </label>
                    <div id="image-preview" _="on load call clearPreviewContainer()"></div>
                </div>
                <button type="submit" class="btn btn-info btn-sm rounded-full text-info-content w-[25%] mt-3">Save</button>
            </form>
        </div>
    </div>

    <script>
        function themeController() {
            const themeRadios = document.querySelectorAll('input[name="theme-dropdown"]');
          
            themeRadios.forEach(radio => {
                radio.addEventListener('change', function () {
                    const selectedTheme = this.value;
                    document.body.setAttribute('data-theme', selectedTheme);              
                });
            });
        }
    
        if (typeof isImagePreviewSetup === "undefined") {
            let isImagePreviewSetup = false;
    
            function setUpImagePreview() {
                console.log("set up image preview");
    
                if (isImagePreviewSetup) {
                    return;
                }
    
                document
                    .getElementById("id_media")
                    .addEventListener("change", function (event) {
                        console.log("preview");
                        const previewContainer =
                            document.getElementById("image-preview");
                        const fileMedia = document.getElementById("id_media");
                        const fileInput = event.target;
                        const files = fileInput.files;
    
                        previewContainer.innerHTML = "";
    
                        if (!files[0].type.startsWith("image/")) {
                            if (files.length === 0) return;
    
                            previewContainer.innerHTML = `<p class='text-red-500'><i class="bx bx-block text-red-500"></i> ${
                                files[0].name.split(".")[files[0].name.split(".").length - 1]
                            } extension is not allowed</p>`;
                            fileMedia.value = "";
    
                            setTimeout(function () {
                                const errorMessage = previewContainer.firstChild;
    
                                if (errorMessage) {
                                    errorMessage.style.transition = "opacity 0.5s";
                                    errorMessage.style.opacity = "0";
    
                                    setTimeout(function () {
                                        previewContainer.innerHTML = "";
                                    }, 500);
                                }
                            }, 3000);
                            return;
                        }
    
                        const reader = new FileReader();
    
                        reader.onload = function (e) {
                            const closeContainer = document.createElement("div");
                            closeContainer.classList.add(
                                "rounded-full",
                                "size-6",
                                "bg-base-300/75",
                                "absolute",
                                "top-1.5",
                                "right-1.5",
                                "cursor-pointer",
                            );
                            const imgElement = document.createElement("img");
                            imgElement.src = e.target.result;
    
                            const closeBtnElement = document.createElement("i");
                            closeBtnElement.classList.add(
                                "bx",
                                "bx-x",
                                "p-1",
                                "bg-transparent",
                                "rounded-full",
                                "hover:bg-base-300/95",
                            );
                            closeBtnElement.id = "image-preview-close";
    
                            closeContainer.appendChild(closeBtnElement);
                            previewContainer.appendChild(closeContainer);
                            previewContainer.appendChild(imgElement);
    
                            document
                                .getElementById("image-preview-close")
                                .addEventListener("click", function () {
                                    console.log("close");
                                    clearPreviewContainer();
                                });
                        };
    
                        reader.readAsDataURL(files[0]);
                    });
                isImagePreviewSetup = true;
            }
        }
    </script>
</div>
{% endblock profile_content %}